menu:
  博客: /blog
  Archives: /blog/archives
  About: /blog/about
  Rss: /blog/atom.xml
  官网: /

root: /blog

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: true
disqus_shortname: wecatch

# google analytics
googleTrackId: UA-79591400-1
